### ISSUE TITLE
Recommend to use Project.toml and CondaPkg.toml?

### ISSUE THREAD

**Issue by shinaoka** [tensor4all/juliaexamples#13]
We may have to describe how to use an environment to avoid compatibility issues.

**Comment by shinaoka** [comment]
Possible solution

*  Describe how to download Project.toml and CondaPkg.toml
* Add something like `Pkg.activate(".")` in each notebook

**Comment by terasakisatoshi** [comment]
`git add Manifest.toml` is good option to reproduce/share environment between multiple users.

**Comment by terasakisatoshi** [comment]
We should pin version of Python since CondaPkg.jl introduces the latest Python which may be too new to be compatible with numpy or matplotlib.

```
# CondaPkg.toml
[deps]
# Conda package names and versions
python = "# specify me"
```

**Comment by terasakisatoshi** [comment]
Oh, we forgot CompatHelper...
